# ==========================================
# docker-compose.yml
# Discord Bot用（ローカル開発 & 永続化対応）
# ==========================================

version: "3.8"
services:
  discord-bot:
    build: .
    container_name: otobot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_LOG_CHANNEL_ID=${ADMIN_LOG_CHANNEL_ID}
      - MODERATOR_ROLE_ID=${MODERATOR_ROLE_ID}
      - SELF_PING_URL=${SELF_PING_URL}  # スリープ防止
    ports:
      - "8080:8080"
